language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
notifications:
  email:
    on_success: change
    on_failure: always
cache:
    directories:
      - node_modules
      - bower_components
      - scripts/vendor
